// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANxyivRoddFfWQ8BPYaHzGK101VXMMYzE',
    appId: '1:429874664647:web:0c48e5f6322a97afad9ae2',
    messagingSenderId: '429874664647',
    projectId: 'appc-4519f',
    authDomain: 'appc-4519f.firebaseapp.com',
    storageBucket: 'appc-4519f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFmKlBY4tVA67lDzRYIfEYEDNnNoOdJwI',
    appId: '1:429874664647:android:18ab300a472ffdc8ad9ae2',
    messagingSenderId: '429874664647',
    projectId: 'appc-4519f',
    storageBucket: 'appc-4519f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_hjTkN08O4GVfLZ82yw7bdRDcEhLlGeA',
    appId: '1:429874664647:ios:baad917b496e327dad9ae2',
    messagingSenderId: '429874664647',
    projectId: 'appc-4519f',
    storageBucket: 'appc-4519f.appspot.com',
    iosBundleId: 'com.example.pruebaIntegradora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_hjTkN08O4GVfLZ82yw7bdRDcEhLlGeA',
    appId: '1:429874664647:ios:baad917b496e327dad9ae2',
    messagingSenderId: '429874664647',
    projectId: 'appc-4519f',
    storageBucket: 'appc-4519f.appspot.com',
    iosBundleId: 'com.example.pruebaIntegradora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANxyivRoddFfWQ8BPYaHzGK101VXMMYzE',
    appId: '1:429874664647:web:2e747ecd21fca9c2ad9ae2',
    messagingSenderId: '429874664647',
    projectId: 'appc-4519f',
    authDomain: 'appc-4519f.firebaseapp.com',
    storageBucket: 'appc-4519f.appspot.com',
  );
}
